import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Brain, BookOpen, TrendingUp, Briefcase, Target, Award } from 'lucide-react';

export interface Feature {
  icon: React.ReactNode;
  title: string;
  description: string;
}

export const FEATURES: Feature[] = [
  {
    icon: <Brain className="w-6 h-6" />,
    title: 'AI-Powered Assessments',
    description: 'Personalized tests generated by AI based on your role, interests, and skill level for accurate evaluation.',
  },
  {
    icon: <BookOpen className="w-6 h-6" />,
    title: 'Course Recommendations',
    description: 'Get tailored course suggestions based on your assessment results to fill skill gaps effectively.',
  },
  {
    icon: <TrendingUp className="w-6 h-6" />,
    title: 'Progress Tracking',
    description: 'Monitor your learning journey with detailed analytics, charts, and insights to measure improvement.',
  },
  {
    icon: <Briefcase className="w-6 h-6" />,
    title: 'Career Guidance',
    description: 'Job-specific assessments and career path recommendations to help you advance professionally.',
  },
  {
    icon: <Target className="w-6 h-6" />,
    title: 'Skill Gap Analysis',
    description: 'Identify areas for improvement with comprehensive skill breakdown and actionable insights.',
  },
  {
    icon: <Award className="w-6 h-6" />,
    title: 'Detailed Reports',
    description: 'Download professional PDF reports with your results, analysis, and personalized recommendations.',
  },
];

export interface FeaturesSectionProps {
  features?: Feature[];
}

export const FeaturesSection: React.FC<FeaturesSectionProps> = ({ 
  features = FEATURES 
}) => {
  return (
    <section id="features" className="py-20 px-4 bg-muted/30">
      <div className="container mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            Everything You Need to Succeed
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Our comprehensive platform provides all the tools and insights you need 
            to assess your skills and advance your career.
          </p>
        </div>
        
        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <Card 
              key={index}
              className="group bg-card/50 backdrop-blur-sm border-border/50 hover:border-primary/50 hover:shadow-lg transition-all duration-300"
              data-testid={`feature-card-${index}`}
            >
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center text-primary mb-4 group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                  {feature.icon}
                </div>
                <h3 
                  className="text-lg font-semibold text-foreground mb-2"
                  data-testid={`feature-title-${index}`}
                >
                  {feature.title}
                </h3>
                <p 
                  className="text-muted-foreground text-sm leading-relaxed"
                  data-testid={`feature-description-${index}`}
                >
                  {feature.description}
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
};
